import Head from "next/head";
import Header from "../components/Header/Header";
import Banner from "../components/Banner/Banner";
import BlogContent from "../components/BlogContent/BlogContent";

export default function Main() {
  return (
    <div>
      <Head>
        <title>Home | BLOG.ryancarmody</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Header />
        <Banner />
        <BlogContent />
      </div>
    </div>
  );
}
