import axios from "axios";
import Head from "next/head";
import PropTypes from "prop-types";
import { useEffect } from "react";
import Header from "../components/Header/Header";
import Banner from "../components/Banner/Banner";
import BlogContent from "../components/BlogContent/BlogContent";

export default function Main() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Header />
        <Banner />
        <BlogContent />
      </div>
    </div>
  );
}
